#pragma once

#include <stdio.h>
#include <tchar.h>
#include <atlbase.h>
#include <atlcom.h>

extern CComModule _Module;

//#import "C:\Github\INACALCPROAdapter\INACALCPROLib\bin\Debug\INACALCPROLib.tlb" no_namespace named_guids rename("EInaValueType_inaValEmpty", "inaValEmpty") rename("EInaValueType_inaValText","inaValText") rename("EInaValueType_inaValNumber","inaValNumber") rename("EInaValueType_inaValDate","inaValDate")  rename("EInaValueType_inaValBool","inaValBool") rename("EInaValueType_inaValError","inaValError") rename("EInaErrorValue_inaErrNone","inaErrNone") rename("EInaErrorValue_inaErrSyntax","inaErrSyntax") rename("EInaErrorValue_inaErrCircRef","inaErrCircRef") rename("EInaErrorValue_inaErrTypeMismatch","inaErrTypeMismatch") rename("EInaErrorValue_inaErrDiv0","inaErrDiv0") rename("EInaErrorValue_inaErrIndefinite","inaErrIndefinite") rename("EInaErrorValue_inaErrInfinite","inaErrInfinite") rename("EInaErrorValue_inaErrInvalidDate","inaErrInvalidDate") rename("EInaErrorValue_inaErrFunc","inaErrFunc") rename("EInaErrorValue_inaErrValue","inaErrValue") rename("EInaErrorValue_inaErrCustFunc","inaErrCustFunc") rename("EInaErrorValue_inaErrRef","inaErrRef") rename("EInaErrorValue_inaErrCount","inaErrCount") rename("EInaFuncCategory_inaFuncArithmetical","inaFuncArithmetical") rename("EInaFuncCategory_inaFuncMathematical","inaFuncMathematical") rename("EInaFuncCategory_inaFuncText","inaFuncText") rename("EInaFuncCategory_inaFuncStatistical","inaFuncStatistical") rename("EInaFuncCategory_inaFuncFinancial","inaFuncFinancial") rename("EInaFuncCategory_inaFuncLogical","inaFuncLogical") rename("EInaFuncCategory_inaFuncDateTime","inaFuncDateTime") rename("EInaFuncCategory_inaFuncCustom","inaFuncCustom")
#import "INACALCPROLib.tlb" no_namespace named_guids rename("EInaValueType_inaValEmpty", "inaValEmpty") rename("EInaValueType_inaValText","inaValText") rename("EInaValueType_inaValNumber","inaValNumber") rename("EInaValueType_inaValDate","inaValDate")  rename("EInaValueType_inaValBool","inaValBool") rename("EInaValueType_inaValError","inaValError") rename("EInaErrorValue_inaErrNone","inaErrNone") rename("EInaErrorValue_inaErrSyntax","inaErrSyntax") rename("EInaErrorValue_inaErrCircRef","inaErrCircRef") rename("EInaErrorValue_inaErrTypeMismatch","inaErrTypeMismatch") rename("EInaErrorValue_inaErrDiv0","inaErrDiv0") rename("EInaErrorValue_inaErrIndefinite","inaErrIndefinite") rename("EInaErrorValue_inaErrInfinite","inaErrInfinite") rename("EInaErrorValue_inaErrInvalidDate","inaErrInvalidDate") rename("EInaErrorValue_inaErrFunc","inaErrFunc") rename("EInaErrorValue_inaErrValue","inaErrValue") rename("EInaErrorValue_inaErrCustFunc","inaErrCustFunc") rename("EInaErrorValue_inaErrRef","inaErrRef") rename("EInaErrorValue_inaErrCount","inaErrCount") rename("EInaFuncCategory_inaFuncArithmetical","inaFuncArithmetical") rename("EInaFuncCategory_inaFuncMathematical","inaFuncMathematical") rename("EInaFuncCategory_inaFuncText","inaFuncText") rename("EInaFuncCategory_inaFuncStatistical","inaFuncStatistical") rename("EInaFuncCategory_inaFuncFinancial","inaFuncFinancial") rename("EInaFuncCategory_inaFuncLogical","inaFuncLogical") rename("EInaFuncCategory_inaFuncDateTime","inaFuncDateTime") rename("EInaFuncCategory_inaFuncCustom","inaFuncCustom")